#!/usr/bin/env node
// Builds everything that gets installed from the readable sources:
//   n8n/clawd-workflow.json, n8n/clawd-workflow-view.json  <- n8n/clawd-engine.js
//   dist/clawd.ax, dist/clawdcore.ax                        <- awtrix/*.ax, minus comments
//
//   node scripts/build.js          write the files
//   node scripts/build.js --check  fail if any of them is out of date
//
// The engine lives in one plain JS file; this script pastes it into the Code
// nodes so the workflow JSON never drifts from the tested source. The Berry
// scripts are installed without comments and indentation, because AWTRIX needs
// free memory of about the source size to compile a script.
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const ENGINE = fs.readFileSync(path.join(ROOT, 'n8n', 'clawd-engine.js'), 'utf8');
const MIRROR = fs.readFileSync(path.join(ROOT, 'n8n', 'clawd-mirror.js'), 'utf8');
const E = require(path.join(ROOT, 'n8n', 'clawd-engine.js'));

// ---- Code node bodies ---------------------------------------------------------
const ENGINE_WRAPPER = `

// ---- n8n wrapper (generated by scripts/build.js) ----------------
const staticData = $getWorkflowStaticData('global');
const results = [];
for (const item of $input.all()) {
  const { cfg, ...input } = item.json;
  const r = ClawdEngine.runN8n(input, staticData, cfg, Date.now());
  if (r.ignore) continue;
  results.push({ json: r });
}
return results;
`;

const MIRROR_WRAPPER = `

// ---- n8n wrapper (generated by scripts/build.js) ----------------
const out = [];
for (const item of $input.all()) {
  if (!item.json.mirror || !item.json.payload) continue;
  out.push({ json: { topic: item.json.mirror, message: ClawdMirror.pngBase64(item.json.payload) } });
}
return out;
`;

const TICK_EVENT = `return [{ json: { event: 'tick' } }];`;

const MQTT_EVENT = `// AWTRIX NG publishes "1" on press and "0" on release (retained), and the
// name of the app on screen as a plain string. Only presses and app changes
// matter; the engine checks the prefix against the Settings node. Anything
// else this trigger receives is the command topic (Home Assistant).
const out = [];
for (const item of $input.all()) {
  const topic = String(item.json.topic || '');
  const msg = String(item.json.message ?? '').trim();
  const at = topic.lastIndexOf('/state/');
  if (at < 0) { if (msg) out.push({ json: { event: 'cmd', payload: msg } }); continue; }
  const prefix = topic.slice(0, at);
  const rest = topic.slice(at + 7).split('/');
  if (rest[0] === 'buttons' && rest.length === 2) {
    if (['1', 'true', 'on'].includes(msg.toLowerCase())) out.push({ json: { event: 'button', btn: rest[1], prefix } });
  } else if (rest[0] === 'apps' && rest[1] === 'active') {
    out.push({ json: { event: 'active', app: msg.replace(/^"|"$/g, ''), prefix } });
  }
}
return out;`;

const HA_EVENT = `// Home Assistant (or anything else) posts {"action":"feed"} to this webhook.
const out = [];
for (const item of $input.all()) {
  const body = item.json.body || item.json;
  const name = String(body.action || '').trim().toLowerCase();
  if (name) out.push({ json: { event: 'action', name } });
}
return out;`;

const CMD_EVENT = `// The on-device view script publishes {"a":"feed"} etc. on the command topic.
return $input.all().map((item) => ({ json: { event: 'cmd', payload: String(item.json.message ?? '') } }));`;

const SPLIT_FRAMES = `// One item per extra frame; the next node sends them 250 ms apart.
const out = [];
for (const item of $input.all()) {
  for (const payload of item.json.frames || []) out.push({ json: { base: item.json.base, app: item.json.app, payload } });
}
return out;`;

// ---- Berry minifier ------------------------------------------------------------------
// Keeps the header tags (# @name, # @config ...), drops every other comment,
// indentation and blank line. Strings are respected, escapes included.
function minifyBerry(src) {
  const out = [];
  let header = true;
  for (const raw of src.split('\n')) {
    const t = raw.trim();
    if (header && (t === '' || t.startsWith('#'))) {
      if (t.startsWith('# @')) out.push(t.replace(/\s+/g, ' '));
      continue;
    }
    header = false;
    let cut = t.length;
    for (let i = 0, q = null; i < t.length; i++) {
      const c = t[i];
      if (q) { if (c === '\\') i++; else if (c === q) q = null; }
      else if (c === '"' || c === "'") q = c;
      else if (c === '#') { cut = i; break; }
    }
    const line = t.slice(0, cut).trimEnd();
    if (line) out.push(line);
  }
  return out.join('\n') + '\n';
}

// ---- node helpers ---------------------------------------------------------------
let seq = 0;
const id = (tag) => `clawd-${tag}-${String(++seq).padStart(2, '0')}`;

function code(name, js, pos, notes) {
  const n = { id: id('code'), name, type: 'n8n-nodes-base.code', typeVersion: 2, position: pos, parameters: { jsCode: js } };
  if (notes) n.notes = notes;
  return n;
}

function ifNode(name, expr, pos) {
  return {
    id: id('if'), name, type: 'n8n-nodes-base.if', typeVersion: 2.2, position: pos,
    parameters: {
      conditions: {
        options: { caseSensitive: true, leftValue: '', typeValidation: 'loose', version: 2 },
        conditions: [{ id: id('cond'), leftValue: `={{ ${expr} }}`, rightValue: '', operator: { type: 'boolean', operation: 'true', singleValue: true } }],
        combinator: 'and'
      },
      options: {}
    }
  };
}

// HTTP calls to AWTRIX never fail the execution: n8n only saves the pet's
// state when an execution succeeds, and a sleeping clock must not cost you a
// feeding.
function http(name, method, urlExpr, bodyExpr, pos, extraOptions) {
  return {
    id: id('http'), name, type: 'n8n-nodes-base.httpRequest', typeVersion: 4.2, position: pos,
    onError: 'continueRegularOutput',
    parameters: {
      method, url: urlExpr, sendBody: true, specifyBody: 'json', jsonBody: bodyExpr,
      options: Object.assign({ timeout: 2000 }, extraOptions || {})
    }
  };
}

function settings(mode, pos) {
  const d = E.DEFAULTS;
  const rows = [
    ['MODE', mode, 'string'],
    ['AWTRIX_HOST', d.AWTRIX_HOST, 'string'],
    ['MQTT_PREFIX', d.MQTT_PREFIX, 'string'],
    ['APP_NAME', d.APP_NAME, 'string'],
    ['PET_NAME', d.PET_NAME, 'string'],
    ['TZ', d.TZ, 'string'],
    ['HUNGER_EMPTY_HOURS', d.HUNGER_EMPTY_HOURS, 'number'],
    ['EGG_HATCH_MIN', d.EGG_HATCH_MIN, 'number'],
    ['CHILD_AT_HOURS', d.CHILD_AT_HOURS, 'number'],
    ['TEEN_AT_HOURS', d.TEEN_AT_HOURS, 'number'],
    ['ADULT_AT_HOURS', d.ADULT_AT_HOURS, 'number'],
    ['SLEEP_FROM', d.SLEEP_FROM, 'number'],
    ['SLEEP_TO', d.SLEEP_TO, 'number'],
    ['NIGHT_FROM', d.NIGHT_FROM, 'number'],
    ['NIGHT_TO', d.NIGHT_TO, 'number'],
    ['SOUND', d.SOUND, 'boolean'],
    ['NOTIFY', d.NOTIFY, 'boolean'],
    ['SWITCH_ON_EVENTS', d.SWITCH_ON_EVENTS, 'boolean']
  ];
  if (mode === 'push') rows.push(['BURST', d.BURST, 'boolean'], ['OFFSCREEN_REFRESH_SEC', d.OFFSCREEN_REFRESH_SEC, 'number'], ['STALE_AFTER_SEC', d.STALE_AFTER_SEC, 'number'],
    ['MIRROR', d.MIRROR, 'boolean'], ['MIRROR_TOPIC', d.MIRROR_TOPIC, 'string']);
  rows.push(['STATE_TOPIC', d.STATE_TOPIC, 'string'], ['CMD_TOPIC', d.CMD_TOPIC, 'string']);
  return {
    id: id('set'), name: 'Settings', type: 'n8n-nodes-base.set', typeVersion: 3.4, position: pos,
    notes: 'All of Clawd\'s settings live here. See README "Settings".',
    parameters: {
      assignments: { assignments: rows.map(([k, v, type]) => ({ id: id('opt'), name: `cfg.${k}`, value: v, type })) },
      includeOtherFields: true,
      options: {}
    }
  };
}

const MQTT_CRED = { mqtt: { id: 'REPLACE_WITH_YOUR_MQTT_CREDENTIAL_ID', name: 'AWTRIX broker' } };

function link(conns, from, to, output) {
  conns[from] = conns[from] || { main: [] };
  const o = output || 0;
  while (conns[from].main.length <= o) conns[from].main.push([]);
  conns[from].main[o].push({ node: to, type: 'main', index: 0 });
}

const WF_SETTINGS = {
  executionOrder: 'v1',
  saveDataSuccessExecution: 'none',   // 43,200 ticks a day are not worth keeping
  saveManualExecutions: true,
  saveExecutionProgress: false,
  callerPolicy: 'workflowsFromSameOwner'
};

// Everything that talks to AWTRIX runs in a background sub-workflow (defined
// inline, so there is nothing extra to import). The run that owns the pet's
// state then ends within milliseconds; see runN8n() in the engine.
function awtrixSubWorkflow(parts) {
  const nodes = [
    { id: id('trg'), name: 'From Clawd Engine', type: 'n8n-nodes-base.executeWorkflowTrigger', typeVersion: 1.1, position: [0, 300],
      parameters: { inputSource: 'passthrough' } }
  ];
  const c = {};
  let y = 0;
  const add = (ifName, expr, httpNode) => {
    nodes.push(ifNode(ifName, expr, [220, y]));
    httpNode.position = [440, y];
    nodes.push(httpNode);
    link(c, 'From Clawd Engine', ifName);
    link(c, ifName, httpNode.name);
    y += 160;
  };
  if (parts.includes('frame')) add('Has Frame', '$json.push === true', http('Push Frame', 'PUT', '={{ $json.base }}/api/v1/apps/pushed/{{ $json.app }}', '={{ JSON.stringify($json.payload) }}'));
  add('Has SwitchTo', '$json.switchTo === true', http('Switch To Clawd', 'PUT', '={{ $json.base }}/api/v1/apps/active', '={{ JSON.stringify({ name: $json.app, fast: true }) }}'));
  if (parts.includes('sound')) add('Has Sound', '!!$json.sound', http('Play Sound', 'POST', '={{ $json.base }}/api/v1/audio/play', '={{ JSON.stringify({ rtttl: $json.sound }) }}'));
  add('Has Notify', '!!$json.notify', http('Send Notify', 'POST', '={{ $json.base }}/api/v1/notifications', '={{ JSON.stringify($json.notify) }}'));
  if (parts.includes('burst')) {
    nodes.push(ifNode('Has Burst', '($json.frames || []).length > 0', [220, y]));
    nodes.push(code('Split Frames', SPLIT_FRAMES, [440, y]));
    nodes.push(http('Push Burst Frame', 'PUT', '={{ $json.base }}/api/v1/apps/pushed/{{ $json.app }}', '={{ JSON.stringify($json.payload) }}', [660, y],
      { batching: { batch: { batchSize: 1, batchInterval: 250 } } }));
    link(c, 'From Clawd Engine', 'Has Burst');
    link(c, 'Has Burst', 'Split Frames');
    link(c, 'Split Frames', 'Push Burst Frame');
  }
  return { name: 'Clawd: send to AWTRIX', nodes, connections: c, settings: { executionOrder: 'v1', saveDataSuccessExecution: 'none' } };
}

function background(name, sub, pos) {
  return {
    id: id('exec'), name, type: 'n8n-nodes-base.executeWorkflow', typeVersion: 1.2, position: pos,
    notes: 'Runs the HTTP calls to AWTRIX in the background. The sub-workflow is defined inline (Workflow JSON).',
    parameters: { source: 'parameter', workflowJson: JSON.stringify(sub, null, 1), mode: 'once', options: { waitForSubWorkflow: false } }
  };
}

function triggers(tickName, tickSec, mqttNode, mqttEventName, mqttEventCode) {
  return [
    { id: id('trg'), name: tickName, type: 'n8n-nodes-base.scheduleTrigger', typeVersion: 1.2, position: [-600, 0],
      parameters: { rule: { interval: [{ field: 'seconds', secondsInterval: tickSec }] } } },
    code('Tick Event', TICK_EVENT, [-380, 0]),
    mqttNode,
    code(mqttEventName, mqttEventCode, [-380, 200]),
    { id: id('trg'), name: 'HA Action (Webhook)', type: 'n8n-nodes-base.webhook', typeVersion: 2, position: [-600, 400],
      webhookId: 'clawd-action',
      notes: 'POST {"action":"feed"} - feed, play, clean, med, sleep, wake, stats, reset.',
      parameters: { httpMethod: 'POST', path: 'clawd-action', responseMode: 'onReceived', options: {} } },
    code('HA Event', HA_EVENT, [-380, 400])
  ];
}

// The retained state line (view app, Home Assistant). An MQTT publish is quick,
// so it stays in the main run, like the view mode always had it.
function publishState(pos) {
  return { id: id('mqtt'), name: 'Publish State', type: 'n8n-nodes-base.mqtt', typeVersion: 1, position: pos,
    credentials: MQTT_CRED, onError: 'continueRegularOutput',
    parameters: { topic: '={{ $json.publish.topic }}', sendInputData: false, message: '={{ $json.publish.message }}', options: { retain: true, qos: 1 } } };
}

// ---- push mode --------------------------------------------------------------------
function pushWorkflow() {
  seq = 0;
  const mqttNode = { id: id('trg'), name: 'AWTRIX MQTT', type: 'n8n-nodes-base.mqttTrigger', typeVersion: 1, position: [-600, 200],
    credentials: MQTT_CRED,
    notes: 'Buttons and the app on screen ("+" stands for your MQTT prefix; if the prefix contains a "/", replace "+" with it), plus the command topic for Home Assistant, which must match CMD_TOPIC in Settings.',
    parameters: { topics: `+/state/buttons/+,+/state/apps/active,${E.DEFAULTS.CMD_TOPIC}`, options: {} } };
  const nodes = triggers('Tick every 2s', 2, mqttNode, 'MQTT Event', MQTT_EVENT).concat([
    settings('push', [-160, 200]),
    code('Clawd Engine', ENGINE + ENGINE_WRAPPER, [60, 200], 'Generated from n8n/clawd-engine.js - edit that file and run scripts/build.js.'),
    ifNode('Has State', '!!$json.publish', [280, 0]),
    publishState([500, 0]),
    ifNode('Anything To Send', '$json.push || $json.switchTo || !!$json.sound || !!$json.notify', [280, 200]),
    background('Send To AWTRIX', awtrixSubWorkflow(['frame', 'sound', 'burst']), [500, 200]),
    ifNode('Has Mirror', '$json.push === true && !!$json.mirror', [280, 400]),
    code('Mirror Frame', MIRROR + MIRROR_WRAPPER, [500, 400], 'Generated from n8n/clawd-mirror.js. Only runs with MIRROR on.'),
    { id: id('mqtt'), name: 'Publish Mirror', type: 'n8n-nodes-base.mqtt', typeVersion: 1, position: [720, 400],
      credentials: MQTT_CRED, onError: 'continueRegularOutput',
      parameters: { topic: '={{ $json.topic }}', sendInputData: false, message: '={{ $json.message }}', options: { retain: true, qos: 0 } } }
  ]);
  const c = {};
  link(c, 'Tick every 2s', 'Tick Event');
  link(c, 'AWTRIX MQTT', 'MQTT Event');
  link(c, 'HA Action (Webhook)', 'HA Event');
  for (const n of ['Tick Event', 'MQTT Event', 'HA Event']) link(c, n, 'Settings');
  link(c, 'Settings', 'Clawd Engine');
  link(c, 'Clawd Engine', 'Has State');
  link(c, 'Has State', 'Publish State');
  link(c, 'Clawd Engine', 'Anything To Send');
  link(c, 'Anything To Send', 'Send To AWTRIX');
  link(c, 'Clawd Engine', 'Has Mirror');
  link(c, 'Has Mirror', 'Mirror Frame');
  link(c, 'Mirror Frame', 'Publish Mirror');
  return { name: 'Clawd (push mode)', nodes, connections: c, active: false, settings: WF_SETTINGS, meta: { clawdEngine: E.ENGINE_VERSION } };
}

// ---- view mode --------------------------------------------------------------------
function viewWorkflow() {
  seq = 0;
  const mqttNode = { id: id('trg'), name: 'Device Commands (MQTT)', type: 'n8n-nodes-base.mqttTrigger', typeVersion: 1, position: [-600, 200],
    credentials: MQTT_CRED,
    notes: 'Must match the "Command topic" setting of the Clawd script and CMD_TOPIC in Settings.',
    parameters: { topics: E.DEFAULTS.CMD_TOPIC, options: {} } };
  const nodes = triggers('Tick every 15s', 15, mqttNode, 'Command Event', CMD_EVENT).concat([
    settings('view', [-160, 200]),
    code('Clawd Engine', ENGINE + ENGINE_WRAPPER, [60, 200], 'Generated from n8n/clawd-engine.js - edit that file and run scripts/build.js.'),
    ifNode('Has State', '!!$json.publish', [280, 100]),
    publishState([500, 100]),
    ifNode('Anything To Send', '$json.switchTo || !!$json.notify', [280, 300]),
    background('Send To AWTRIX', awtrixSubWorkflow([]), [500, 300])
  ]);
  const c = {};
  link(c, 'Tick every 15s', 'Tick Event');
  link(c, 'Device Commands (MQTT)', 'Command Event');
  link(c, 'HA Action (Webhook)', 'HA Event');
  for (const n of ['Tick Event', 'Command Event', 'HA Event']) link(c, n, 'Settings');
  link(c, 'Settings', 'Clawd Engine');
  link(c, 'Clawd Engine', 'Has State');
  link(c, 'Clawd Engine', 'Anything To Send');
  link(c, 'Has State', 'Publish State');
  link(c, 'Anything To Send', 'Send To AWTRIX');
  return { name: 'Clawd (view mode)', nodes, connections: c, active: false, settings: WF_SETTINGS, meta: { clawdEngine: E.ENGINE_VERSION } };
}

// ---- main ---------------------------------------------------------------------------
const json = (wf) => JSON.stringify(wf, null, 2) + '\n';
const berry = (f) => minifyBerry(fs.readFileSync(path.join(ROOT, 'awtrix', f), 'utf8'));
const outputs = {
  'n8n/clawd-workflow.json': json(pushWorkflow()),
  'n8n/clawd-workflow-view.json': json(viewWorkflow()),
  'dist/clawd.ax': berry('clawd-view.ax'),
  'dist/clawdcore.ax': berry('clawdcore.ax')
};
const check = process.argv.includes('--check');
let stale = 0;
fs.mkdirSync(path.join(ROOT, 'dist'), { recursive: true });
for (const [rel, text] of Object.entries(outputs)) {
  const file = path.join(ROOT, rel);
  if (check) {
    const cur = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : '';
    if (cur !== text) { console.error(`${rel} is out of date - run: node scripts/build.js`); stale++; }
  } else {
    fs.writeFileSync(file, text);
    console.log(`wrote ${rel} (${text.length} bytes)`);
  }
}
if (stale) process.exit(1);
